name: OptiVision
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  get: ^4.6.5
  open_file: ^3.5.10
  shared_preferences: ^2.0.15
  pdf: ^3.8.0
  file_picker: ^5.2.2
  printing: ^5.6.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  line_awesome_flutter: ^3.0.1
  font_awesome_flutter: ^10.7.0
  table_calendar: ^3.1.2
  intl: ^0.19.0
  flutter_stripe: ^11.2.0
  network_info_plus: ^6.0.2
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  animations: ^2.0.11
  flutter_rating_bar: ^4.0.1

  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/OptiVision.png"

flutter:

  uses-material-design: true

  assets:
   - assets/images/

